### ISSUE TITLE
Group capstone: set up your Kanban board-16/05/2022-https://github.com/ONJoseph/JavaScriptCapstone/projects/1

### ISSUE THREAD

**Issue by ONJoseph** [ONJoseph/JavaScriptCapstone#21]
- Project Link: https://github.com/ONJoseph/JavaScriptCapstone/projects/1
- Please Note: We are just two(2) persons on this team.

**Comment by keroloussamy** [comment]
Hi Team, 

Your project is complete
Congratulations! 🎉 


![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
